remote_theme: nrandecker/particle
#site settings
title: Martin Vazquez | Portfolio
description: Martin Vazquez | Portfolio

username: Martin Vazquez
user_description: As I approach the end of my time at DePaul University, I'm looking for any opportunity to apply what I've learned in the classroom to the real world. I thrive in environments where I can make a tangible impact helping others in some way. Being a student in Chicago brings me more opportunities than most, and I'm incredibly thankful to call such a great place my home. 
user_title: DePaul 2020  i like turtles

email: mvazqu37@depaul.edu
github_username: mv4z
twitter_username: mazzquezzz

exclude: ['package.json', 'node_modules']